/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 30
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_COLON = 2,
  anon_sym_EQ = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_DASH = 6,
  anon_sym_PLUS = 7,
  anon_sym_STAR = 8,
  anon_sym_SLASH = 9,
  sym_number = 10,
  sym_identifier = 11,
  anon_sym_DOT = 12,
  sym_result_comment = 13,
  sym_comment = 14,
  sym_source_file = 15,
  sym__line = 16,
  sym_statement = 17,
  sym_section_header = 18,
  sym_assignment_statement = 19,
  sym_expression_statement = 20,
  sym_expression = 21,
  sym_parenthesized_expression = 22,
  sym_unary_expression = 23,
  sym_binary_expression = 24,
  sym_qualified_identifier = 25,
  aux_sym_source_file_repeat1 = 26,
  aux_sym_qualified_identifier_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_number] = "number",
  [sym_identifier] = "identifier",
  [anon_sym_DOT] = ".",
  [sym_result_comment] = "result_comment",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_statement] = "statement",
  [sym_section_header] = "section_header",
  [sym_assignment_statement] = "assignment_statement",
  [sym_expression_statement] = "expression_statement",
  [sym_expression] = "expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_qualified_identifier] = "qualified_identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_qualified_identifier_repeat1] = "qualified_identifier_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_number] = sym_number,
  [sym_identifier] = sym_identifier,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_result_comment] = sym_result_comment,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_statement] = sym_statement,
  [sym_section_header] = sym_section_header,
  [sym_assignment_statement] = sym_assignment_statement,
  [sym_expression_statement] = sym_expression_statement,
  [sym_expression] = sym_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_qualified_identifier] = sym_qualified_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_qualified_identifier_repeat1] = aux_sym_qualified_identifier_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_result_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_qualified_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_left = 2,
  field_name = 3,
  field_operator = 4,
  field_right = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_argument, 1},
    {field_operator, 0},
  [2] =
    {field_name, 0},
  [3] =
    {field_name, 0},
    {field_value, 2},
  [5] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '\n', 5,
        '#', 20,
        '(', 8,
        ')', 9,
        '*', 12,
        '+', 11,
        '-', 10,
        '.', 18,
        '/', 13,
        ':', 6,
        '=', 7,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 1:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 2:
      if (eof) ADVANCE(4);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '(') ADVANCE(8);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == '.') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '\n', 5,
        '#', 20,
        ')', 9,
        '*', 12,
        '+', 11,
        '-', 10,
        '.', 17,
        '/', 13,
        ':', 6,
        '=', 7,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_result_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '=') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 2},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_result_comment] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(27),
    [sym__line] = STATE(2),
    [sym_statement] = STATE(23),
    [sym_section_header] = STATE(24),
    [sym_assignment_statement] = STATE(24),
    [sym_expression_statement] = STATE(24),
    [sym_expression] = STATE(19),
    [sym_parenthesized_expression] = STATE(14),
    [sym_unary_expression] = STATE(14),
    [sym_binary_expression] = STATE(14),
    [sym_qualified_identifier] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_LF] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_result_comment] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__line] = STATE(3),
    [sym_statement] = STATE(26),
    [sym_section_header] = STATE(24),
    [sym_assignment_statement] = STATE(24),
    [sym_expression_statement] = STATE(24),
    [sym_expression] = STATE(19),
    [sym_parenthesized_expression] = STATE(14),
    [sym_unary_expression] = STATE(14),
    [sym_binary_expression] = STATE(14),
    [sym_qualified_identifier] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_LF] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_result_comment] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
  },
  [STATE(3)] = {
    [sym__line] = STATE(3),
    [sym_statement] = STATE(29),
    [sym_section_header] = STATE(24),
    [sym_assignment_statement] = STATE(24),
    [sym_expression_statement] = STATE(24),
    [sym_expression] = STATE(19),
    [sym_parenthesized_expression] = STATE(14),
    [sym_unary_expression] = STATE(14),
    [sym_binary_expression] = STATE(14),
    [sym_qualified_identifier] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_LF] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(28),
    [anon_sym_DASH] = ACTIONS(31),
    [sym_number] = ACTIONS(34),
    [sym_identifier] = ACTIONS(37),
    [sym_result_comment] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_COLON,
    ACTIONS(44), 1,
      anon_sym_EQ,
    ACTIONS(46), 1,
      anon_sym_DOT,
    STATE(10), 1,
      aux_sym_qualified_identifier_repeat1,
    ACTIONS(40), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [27] = 8,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(48), 1,
      sym_identifier,
    STATE(15), 1,
      sym_expression,
    STATE(14), 4,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_qualified_identifier,
  [55] = 8,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(48), 1,
      sym_identifier,
    STATE(22), 1,
      sym_expression,
    STATE(14), 4,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_qualified_identifier,
  [83] = 5,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_DOT,
    STATE(10), 1,
      aux_sym_qualified_identifier_repeat1,
    ACTIONS(40), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [105] = 8,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(48), 1,
      sym_identifier,
    STATE(21), 1,
      sym_expression,
    STATE(14), 4,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_qualified_identifier,
  [133] = 8,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(48), 1,
      sym_identifier,
    STATE(18), 1,
      sym_expression,
    STATE(14), 4,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_qualified_identifier,
  [161] = 5,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_DOT,
    STATE(12), 1,
      aux_sym_qualified_identifier_repeat1,
    ACTIONS(50), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [183] = 8,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(48), 1,
      sym_identifier,
    STATE(17), 1,
      sym_expression,
    STATE(14), 4,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_qualified_identifier,
  [211] = 5,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_DOT,
    STATE(12), 1,
      aux_sym_qualified_identifier_repeat1,
    ACTIONS(52), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [233] = 3,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(52), 8,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
  [250] = 3,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(57), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [266] = 3,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(59), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [282] = 3,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(61), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [298] = 4,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(65), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(63), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
  [316] = 3,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(63), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [332] = 5,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(65), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(69), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [351] = 3,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(71), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_LPAREN,
      anon_sym_DASH,
      sym_number,
      sym_identifier,
  [366] = 5,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(65), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(69), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [385] = 5,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_RPAREN,
    ACTIONS(65), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(69), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [403] = 4,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 1,
      anon_sym_LF,
  [416] = 3,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [427] = 3,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [438] = 4,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_LF,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
  [451] = 3,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
  [461] = 3,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(87), 1,
      sym_identifier,
  [471] = 3,
    ACTIONS(3), 1,
      sym_result_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 27,
  [SMALL_STATE(6)] = 55,
  [SMALL_STATE(7)] = 83,
  [SMALL_STATE(8)] = 105,
  [SMALL_STATE(9)] = 133,
  [SMALL_STATE(10)] = 161,
  [SMALL_STATE(11)] = 183,
  [SMALL_STATE(12)] = 211,
  [SMALL_STATE(13)] = 233,
  [SMALL_STATE(14)] = 250,
  [SMALL_STATE(15)] = 266,
  [SMALL_STATE(16)] = 282,
  [SMALL_STATE(17)] = 298,
  [SMALL_STATE(18)] = 316,
  [SMALL_STATE(19)] = 332,
  [SMALL_STATE(20)] = 351,
  [SMALL_STATE(21)] = 366,
  [SMALL_STATE(22)] = 385,
  [SMALL_STATE(23)] = 403,
  [SMALL_STATE(24)] = 416,
  [SMALL_STATE(25)] = 427,
  [SMALL_STATE(26)] = 438,
  [SMALL_STATE(27)] = 451,
  [SMALL_STATE(28)] = 461,
  [SMALL_STATE(29)] = 471,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_identifier, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_identifier, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_qualified_identifier_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_qualified_identifier_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 1),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 4),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_statement, 3, 0, 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 2, 0, 2),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_calc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "calc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
